/**
 * Chart of Accounts controller.
 * Account codes are generated by the backend from the parent account —
 * the frontend never submits one.
 */
const coaModel = require('../models/financeCoaModel');
const accountingService = require('../services/accountingService');
const { success, error } = require('../utils/response');
const { wrap } = require('../utils/helpers');

function profileFields(body) {
  return {
    title: body.Title,
    knockOff: body.KnockOff === true,
    bookType: body.BookType || null,
    branchId: body.BranchID || null,
    isActive: body.IsActive,
    description: body.Description || null,
    referenceNo: body.ReferenceNo || null,
    address: body.Address || null,
    phone: body.Phone || null,
    whatsapp: body.Whatsapp || body.WhatsApp || null,
    telephone: body.Telephone || null,
    fax: body.Fax || null,
    email: body.Email || null,
    cnic: body.Cnic || body.CNIC || null,
    ntn: body.Ntn || body.NTN || null,
    strn: body.Strn || body.STRN || null,
    bankName: body.BankName || null,
    bankAccountTitle: body.BankAccountTitle || null,
    bankAccountNo: body.BankAccountNo || null,
    iban: body.IBAN || null,
    bankBranch: body.BankBranch || null,
    tags: body.Tags || null,
  };
}

exports.getStructure = wrap(async (req, res) => {
  const data = await accountingService.call(() => coaModel.getStructure());
  return success(res, data, 'COA structure');
});

exports.setStructure = wrap(async (req, res) => {
  await accountingService.call(() => coaModel.setStructure(req.body.Levels, req.user.userId));
  res.locals.auditDetails = { levels: req.body.Levels };
  return success(res, null, 'COA structure updated');
});

exports.list = wrap(async (req, res) => {
  const rows = await accountingService.call(() => coaModel.list({
    search: req.query.search || null,
    accountType: req.query.accountType || null,
    isControl: req.query.isControl,
    isActive: req.query.isActive,
    tag: req.query.tag || null,
    includeDeleted: req.query.includeDeleted === 'true',
  }));
  return success(res, rows, 'Chart of accounts');
});

exports.get = wrap(async (req, res) => {
  const data = await accountingService.call(() => coaModel.get(parseInt(req.params.id, 10)));
  if (!data.account) return error(res, 'Account not found', 404, 'NOT_FOUND');
  return success(res, data, 'Account');
});

/** Preview of the code the system will generate under the given parent. */
exports.nextCode = wrap(async (req, res) => {
  const parentId = parseInt(req.query.parentId, 10);
  const data = await accountingService.call(() => coaModel.nextCode(parentId));
  return success(res, data, 'Next account code');
});

exports.create = wrap(async (req, res) => {
  const fields = profileFields(req.body);
  const result = await accountingService.call(() => coaModel.create({
    ...fields,
    parentId: req.body.ParentAccountID ? Number(req.body.ParentAccountID) : null,
    isControl: req.body.IsControl !== false,
  }, req.user.userId));
  res.locals.entityId = result.AccountID;
  res.locals.auditDetails = { code: result.Code, title: fields.title, parent: req.body.ParentAccountID };
  return success(res, result, 'Account created', null, 201);
});

exports.update = wrap(async (req, res) => {
  await accountingService.call(() => coaModel.update(parseInt(req.params.id, 10), {
    ...profileFields(req.body),
  }, req.user.userId));
  res.locals.entityId = parseInt(req.params.id, 10);
  res.locals.auditDetails = { title: req.body.Title, tags: req.body.Tags, knockOff: req.body.KnockOff };
  return success(res, null, 'Account updated');
});

exports.setStatus = wrap(async (req, res) => {
  await accountingService.call(() => coaModel.setStatus(
    parseInt(req.params.id, 10), req.body.IsActive, req.user.userId));
  res.locals.entityId = parseInt(req.params.id, 10);
  res.locals.auditDetails = { isActive: req.body.IsActive };
  return success(res, null, req.body.IsActive ? 'Account activated' : 'Account deactivated');
});

exports.remove = wrap(async (req, res) => {
  await accountingService.call(() => coaModel.remove(parseInt(req.params.id, 10), req.user.userId));
  res.locals.entityId = parseInt(req.params.id, 10);
  return success(res, null, 'Account deleted');
});

exports.selector = wrap(async (req, res) => {
  // branch availability: normal users only see All-Branches + own-branch accounts
  const branchId = req.user.isSuperAdmin
    ? (req.query.branchId ? parseInt(req.query.branchId, 10) : null)
    : req.user.branchId;
  const rows = await accountingService.call(() => coaModel.selector({
    tag: req.query.tag || null,
    bookType: req.query.bookType || null,
    branchId,
    search: req.query.search || null,
    topN: req.query.limit ? parseInt(req.query.limit, 10) : 200,
  }));
  return success(res, rows, 'Account selector');
});

exports.setPhoto = wrap(async (req, res) => {
  if (!req.file || !req.file.buffer) return error(res, 'Photo file is required', 400, 'BAD_REQUEST');
  const id = parseInt(req.params.id, 10);
  await accountingService.call(() => coaModel.setPhoto(id, req.file.buffer, req.user.userId));
  res.locals.entityId = id;
  return success(res, null, 'Account photo updated');
});
