// Generate SQL Server (T-SQL) schema + seed from the Prisma schema and current DB data
import { PrismaClient } from '@prisma/client'
import { writeFileSync } from 'fs'

const db = new PrismaClient()

// Maps Prisma/SQLite types to SQL Server types
const typeMap: Record<string, string> = {
  String: 'NVARCHAR(500)',
  'String?': 'NVARCHAR(500)',
  Int: 'INT',
  'Int?': 'INT',
  Float: 'FLOAT',
  'Float?': 'FLOAT',
  Boolean: 'BIT',
  'Boolean?': 'BIT',
  DateTime: 'DATETIME2',
  'DateTime?': 'DATETIME2',
}

const tables = [
  { name: 'Company', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['companyId', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['name', 'NVARCHAR(200) NOT NULL'],
    ['address', 'NVARCHAR(500)'],
    ['phone', 'NVARCHAR(50)'],
    ['email', 'NVARCHAR(200)'],
    ['website', 'NVARCHAR(200)'],
    ['logo', 'NVARCHAR(500)'],
    ['accountingType', 'NVARCHAR(20) NOT NULL DEFAULT \'FIFO\''],
    ['strn', 'NVARCHAR(50)'],
    ['ntn', 'NVARCHAR(50)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'Branch', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['address', 'NVARCHAR(500)'],
    ['city', 'NVARCHAR(100)'],
    ['phone', 'NVARCHAR(30)'],
    ['email', 'NVARCHAR(150)'],
    ['strn', 'NVARCHAR(50)'],
    ['ntn', 'NVARCHAR(50)'],
    ['logo', 'NVARCHAR(500)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['isDeleted', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'Role', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['description', 'NVARCHAR(300)'],
    ['isSystem', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'Permission', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['module', 'NVARCHAR(50) NOT NULL'],
    ['action', 'NVARCHAR(30) NOT NULL'],
    ['code', 'NVARCHAR(100) NOT NULL UNIQUE'],
    ['description', 'NVARCHAR(200)'],
  ]},
  { name: 'RolePermission', cols: [
    ['roleId', 'NVARCHAR(50) NOT NULL'],
    ['permissionId', 'NVARCHAR(50) NOT NULL'],
    ['CONSTRAINT PK_RolePermissions PRIMARY KEY (roleId, permissionId)'],
    ['CONSTRAINT FK_RolePermissions_Role FOREIGN KEY (roleId) REFERENCES Roles(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_RolePermissions_Permission FOREIGN KEY (permissionId) REFERENCES Permissions(id) ON DELETE CASCADE'],
  ]},
  { name: 'User', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['username', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['email', 'NVARCHAR(150) UNIQUE'],
    ['fullName', 'NVARCHAR(150) NOT NULL'],
    ['passwordHash', 'NVARCHAR(255) NOT NULL'],
    ['roleId', 'NVARCHAR(50) NOT NULL'],
    ['branchId', 'NVARCHAR(50)'],
    ['accessibleBranchIds', 'NVARCHAR(2000) NOT NULL DEFAULT \'*\''],
    ['phone', 'NVARCHAR(30)'],
    ['photo', 'NVARCHAR(500)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['failedLoginCount', 'INT NOT NULL DEFAULT 0'],
    ['lastLoginAt', 'DATETIME2'],
    ['mustChangePassword', 'BIT NOT NULL DEFAULT 0'],
    ['isDeleted', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Users_Role FOREIGN KEY (roleId) REFERENCES Roles(id)'],
    ['CONSTRAINT FK_Users_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'Session', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['userId', 'NVARCHAR(50) NOT NULL'],
    ['refreshToken', 'NVARCHAR(500) NOT NULL'],
    ['ipAddress', 'NVARCHAR(50)'],
    ['userAgent', 'NVARCHAR(500)'],
    ['location', 'NVARCHAR(200)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['expiresAt', 'DATETIME2 NOT NULL'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Sessions_User FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE'],
  ]},
  { name: 'AuditLog', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['userId', 'NVARCHAR(50)'],
    ['action', 'NVARCHAR(50) NOT NULL'],
    ['module', 'NVARCHAR(50) NOT NULL'],
    ['details', 'NVARCHAR(MAX)'],
    ['ipAddress', 'NVARCHAR(50)'],
    ['location', 'NVARCHAR(200)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_AuditLog_User FOREIGN KEY (userId) REFERENCES Users(id)'],
  ]},
  { name: 'Account', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['name', 'NVARCHAR(200) NOT NULL'],
    ['parentId', 'NVARCHAR(50)'],
    ['accountType', 'NVARCHAR(30) NOT NULL'],
    ['bookType', 'NVARCHAR(20)'],
    ['accountTag', 'NVARCHAR(30)'],
    ['isControl', 'BIT NOT NULL DEFAULT 0'],
    ['isDetail', 'BIT NOT NULL DEFAULT 1'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['branchId', 'NVARCHAR(50)'],
    ['contactName', 'NVARCHAR(150)'],
    ['phone', 'NVARCHAR(30)'],
    ['email', 'NVARCHAR(150)'],
    ['address', 'NVARCHAR(500)'],
    ['bankName', 'NVARCHAR(100)'],
    ['bankAccountNo', 'NVARCHAR(50)'],
    ['bankBranch', 'NVARCHAR(100)'],
    ['cnic', 'NVARCHAR(30)'],
    ['ntn', 'NVARCHAR(30)'],
    ['description', 'NVARCHAR(500)'],
    ['openingBalance', 'FLOAT NOT NULL DEFAULT 0'],
    ['openingBalanceType', 'NVARCHAR(5)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Account_Parent FOREIGN KEY (parentId) REFERENCES Accounts(id)'],
    ['CONSTRAINT FK_Account_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'FinancialYear', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['startDate', 'DATETIME2 NOT NULL'],
    ['endDate', 'DATETIME2 NOT NULL'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['isClosed', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'AccountingPeriod', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['financialYearId', 'NVARCHAR(50) NOT NULL'],
    ['name', 'NVARCHAR(50) NOT NULL'],
    ['startDate', 'DATETIME2 NOT NULL'],
    ['endDate', 'DATETIME2 NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Open\''],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Period_FY FOREIGN KEY (financialYearId) REFERENCES FinancialYears(id)'],
  ]},
  { name: 'TaxHead', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['shortName', 'NVARCHAR(50) NOT NULL'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['taxType', 'NVARCHAR(30) NOT NULL'],
    ['rate', 'FLOAT NOT NULL'],
    ['branchId', 'NVARCHAR(50)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_TaxHead_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'Voucher', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['voucherNo', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['voucherType', 'NVARCHAR(20) NOT NULL'],
    ['voucherDate', 'DATETIME2 NOT NULL'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['bookAccountId', 'NVARCHAR(50)'],
    ['description', 'NVARCHAR(500)'],
    ['reference', 'NVARCHAR(100)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Draft\''],
    ['postedById', 'NVARCHAR(50)'],
    ['postedAt', 'DATETIME2'],
    ['reversedById', 'NVARCHAR(50)'],
    ['reversedAt', 'DATETIME2'],
    ['reversalReason', 'NVARCHAR(500)'],
    ['totalDebit', 'FLOAT NOT NULL DEFAULT 0'],
    ['totalCredit', 'FLOAT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Voucher_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_Voucher_BookAccount FOREIGN KEY (bookAccountId) REFERENCES Accounts(id)'],
  ]},
  { name: 'VoucherLine', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['voucherId', 'NVARCHAR(50) NOT NULL'],
    ['accountId', 'NVARCHAR(50) NOT NULL'],
    ['lineDescription', 'NVARCHAR(500)'],
    ['title', 'NVARCHAR(200)'],
    ['reference', 'NVARCHAR(100)'],
    ['amount', 'FLOAT NOT NULL DEFAULT 0'],
    ['debit', 'FLOAT NOT NULL DEFAULT 0'],
    ['credit', 'FLOAT NOT NULL DEFAULT 0'],
    ['taxAccountId', 'NVARCHAR(50)'],
    ['taxRate', 'FLOAT NOT NULL DEFAULT 0'],
    ['taxAmount', 'FLOAT NOT NULL DEFAULT 0'],
    ['chequeNo', 'NVARCHAR(50)'],
    ['chequeAmount', 'FLOAT'],
    ['chequeBankName', 'NVARCHAR(100)'],
    ['chequeStatus', 'NVARCHAR(20)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_VoucherLine_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_VoucherLine_Account FOREIGN KEY (accountId) REFERENCES Accounts(id)'],
  ]},
  { name: 'Cheque', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['voucherId', 'NVARCHAR(50) NOT NULL'],
    ['chequeNo', 'NVARCHAR(50) NOT NULL'],
    ['chequeDate', 'DATETIME2 NOT NULL'],
    ['bankName', 'NVARCHAR(100)'],
    ['amount', 'FLOAT NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Hold\''],
    ['statusChangedAt', 'DATETIME2'],
    ['statusChangedBy', 'NVARCHAR(50)'],
    ['statusHistory', 'NVARCHAR(MAX)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Cheque_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id) ON DELETE CASCADE'],
  ]},
  { name: 'AccountMapping', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['branchId', 'NVARCHAR(50)'],
    ['key', 'NVARCHAR(50) NOT NULL'],
    ['accountId', 'NVARCHAR(50) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_AccountMapping_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_AccountMapping_Account FOREIGN KEY (accountId) REFERENCES Accounts(id)'],
    ['CONSTRAINT UQ_AccountMapping_BranchKey UNIQUE (branchId, key)'],
  ]},
  { name: 'MembershipPlan', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['name', 'NVARCHAR(100) NOT NULL'],
    ['durationDays', 'INT NOT NULL'],
    ['amount', 'FLOAT NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'Member', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['firstName', 'NVARCHAR(100) NOT NULL'],
    ['lastName', 'NVARCHAR(100)'],
    ['gender', 'NVARCHAR(20)'],
    ['dob', 'DATETIME2'],
    ['phone', 'NVARCHAR(30)'],
    ['whatsapp', 'NVARCHAR(30)'],
    ['email', 'NVARCHAR(150)'],
    ['address', 'NVARCHAR(500)'],
    ['emergencyContact', 'NVARCHAR(100)'],
    ['emergencyContactNo', 'NVARCHAR(30)'],
    ['photo', 'NVARCHAR(500)'],
    ['cnic', 'NVARCHAR(30)'],
    ['joiningDate', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['billingStartDate', 'DATETIME2'],
    ['feeRelaxationDays', 'INT NOT NULL DEFAULT 0'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['membershipPlanId', 'NVARCHAR(50)'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['assignedTrainerId', 'NVARCHAR(50)'],
    ['notes', 'NVARCHAR(MAX)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['isDeleted', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Member_Plan FOREIGN KEY (membershipPlanId) REFERENCES MembershipPlans(id)'],
    ['CONSTRAINT FK_Member_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'Attendance', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['date', 'DATETIME2 NOT NULL'],
    ['checkIn', 'DATETIME2'],
    ['checkOut', 'DATETIME2'],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Attendance_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_Attendance_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT UQ_Attendance_MemberDate UNIQUE (memberId, date)'],
  ]},
  { name: 'Fee', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['feeNo', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['billingPeriodStart', 'DATETIME2 NOT NULL'],
    ['billingPeriodEnd', 'DATETIME2 NOT NULL'],
    ['amount', 'FLOAT NOT NULL'],
    ['discount', 'FLOAT NOT NULL DEFAULT 0'],
    ['paidAmount', 'FLOAT NOT NULL DEFAULT 0'],
    ['balance', 'FLOAT NOT NULL DEFAULT 0'],
    ['dueDate', 'DATETIME2 NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Unpaid\''],
    ['paymentMethod', 'NVARCHAR(20)'],
    ['paymentAccountId', 'NVARCHAR(50)'],
    ['paymentDate', 'DATETIME2'],
    ['reference', 'NVARCHAR(100)'],
    ['voucherId', 'NVARCHAR(50)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Fee_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_Fee_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_Fee_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id)'],
  ]},
  { name: 'FeePayment', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['feeId', 'NVARCHAR(50) NOT NULL'],
    ['voucherId', 'NVARCHAR(50) NOT NULL'],
    ['amount', 'FLOAT NOT NULL'],
    ['method', 'NVARCHAR(20) NOT NULL'],
    ['accountId', 'NVARCHAR(50) NOT NULL'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_FeePayment_Fee FOREIGN KEY (feeId) REFERENCES Fees(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_FeePayment_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id)'],
  ]},
  { name: 'Prospect', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['prospectId', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['phone', 'NVARCHAR(30)'],
    ['whatsapp', 'NVARCHAR(30)'],
    ['gender', 'NVARCHAR(20)'],
    ['age', 'INT'],
    ['dob', 'DATETIME2'],
    ['interestedMembership', 'NVARCHAR(200)'],
    ['preferredBranchId', 'NVARCHAR(50)'],
    ['source', 'NVARCHAR(30) NOT NULL DEFAULT \'WalkIn\''],
    ['status', 'NVARCHAR(30) NOT NULL DEFAULT \'New\''],
    ['inquiryDate', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['followUpDate', 'DATETIME2'],
    ['assignedTo', 'NVARCHAR(50)'],
    ['notes', 'NVARCHAR(MAX)'],
    ['convertedMemberId', 'NVARCHAR(50)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Prospect_Branch FOREIGN KEY (preferredBranchId) REFERENCES Branches(id)'],
  ]},
  { name: 'MembershipFreeze', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['freezeFrom', 'DATETIME2 NOT NULL'],
    ['freezeTo', 'DATETIME2 NOT NULL'],
    ['days', 'INT NOT NULL'],
    ['reason', 'NVARCHAR(500)'],
    ['approvedBy', 'NVARCHAR(50)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Freeze_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_Freeze_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'FollowUp', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50)'],
    ['prospectId', 'NVARCHAR(50)'],
    ['branchId', 'NVARCHAR(50)'],
    ['date', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['type', 'NVARCHAR(30) NOT NULL'],
    ['userId', 'NVARCHAR(50)'],
    ['notes', 'NVARCHAR(MAX)'],
    ['outcome', 'NVARCHAR(50)'],
    ['nextFollowUpDate', 'DATETIME2'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_FollowUp_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_FollowUp_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'Exercise', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['category', 'NVARCHAR(50)'],
    ['muscleGroup', 'NVARCHAR(50)'],
    ['instructions', 'NVARCHAR(MAX)'],
    ['sets', 'INT'],
    ['reps', 'NVARCHAR(20)'],
    ['duration', 'NVARCHAR(20)'],
    ['rest', 'NVARCHAR(20)'],
    ['equipment', 'NVARCHAR(100)'],
    ['image', 'NVARCHAR(500)'],
    ['branchId', 'NVARCHAR(50)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Exercise_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'WorkoutPlan', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['isGeneral', 'BIT NOT NULL DEFAULT 1'],
    ['branchId', 'NVARCHAR(50)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_WorkoutPlan_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'WorkoutDay', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['planId', 'NVARCHAR(50) NOT NULL'],
    ['dayName', 'NVARCHAR(50) NOT NULL'],
    ['notes', 'NVARCHAR(500)'],
    ['CONSTRAINT FK_WorkoutDay_Plan FOREIGN KEY (planId) REFERENCES WorkoutPlans(id) ON DELETE CASCADE'],
  ]},
  { name: 'WorkoutDayExercise', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['dayId', 'NVARCHAR(50) NOT NULL'],
    ['exerciseId', 'NVARCHAR(50) NOT NULL'],
    ['sets', 'INT'],
    ['reps', 'NVARCHAR(20)'],
    ['duration', 'NVARCHAR(20)'],
    ['rest', 'NVARCHAR(20)'],
    ['notes', 'NVARCHAR(500)'],
    ['CONSTRAINT FK_WDE_Day FOREIGN KEY (dayId) REFERENCES WorkoutDays(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_WDE_Exercise FOREIGN KEY (exerciseId) REFERENCES Exercises(id)'],
  ]},
  { name: 'WorkoutAssignment', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['planId', 'NVARCHAR(50)'],
    ['trainerId', 'NVARCHAR(50)'],
    ['startDate', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['endDate', 'DATETIME2'],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_WA_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_WA_Plan FOREIGN KEY (planId) REFERENCES WorkoutPlans(id)'],
  ]},
  { name: 'DietPlan', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['branchId', 'NVARCHAR(50)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_DietPlan_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'DietMeal', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['planId', 'NVARCHAR(50) NOT NULL'],
    ['timing', 'NVARCHAR(50) NOT NULL'],
    ['foods', 'NVARCHAR(500)'],
    ['quantity', 'NVARCHAR(50)'],
    ['calories', 'FLOAT'],
    ['protein', 'FLOAT'],
    ['carbs', 'FLOAT'],
    ['fat', 'FLOAT'],
    ['notes', 'NVARCHAR(500)'],
    ['CONSTRAINT FK_DietMeal_Plan FOREIGN KEY (planId) REFERENCES DietPlans(id) ON DELETE CASCADE'],
  ]},
  { name: 'DietAssignment', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['planId', 'NVARCHAR(50) NOT NULL'],
    ['startDate', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['endDate', 'DATETIME2'],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_DA_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_DA_Plan FOREIGN KEY (planId) REFERENCES DietPlans(id)'],
  ]},
  { name: 'ProgressEntry', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['memberId', 'NVARCHAR(50) NOT NULL'],
    ['date', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['weight', 'FLOAT'],
    ['chest', 'FLOAT'],
    ['waist', 'FLOAT'],
    ['hips', 'FLOAT'],
    ['biceps', 'FLOAT'],
    ['thighs', 'FLOAT'],
    ['notes', 'NVARCHAR(500)'],
    ['photo', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Progress_Member FOREIGN KEY (memberId) REFERENCES Members(id) ON DELETE CASCADE'],
  ]},
  { name: 'Equipment', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['category', 'NVARCHAR(50) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['purchaseDate', 'DATETIME2'],
    ['purchasePrice', 'FLOAT'],
    ['quantity', 'INT NOT NULL DEFAULT 1'],
    ['condition', 'NVARCHAR(30) NOT NULL DEFAULT \'Working\''],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['billReference', 'NVARCHAR(50)'],
    ['billImage', 'NVARCHAR(500)'],
    ['image', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Equipment_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'EquipmentMaintenance', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['equipmentId', 'NVARCHAR(50) NOT NULL'],
    ['date', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['type', 'NVARCHAR(50) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['cost', 'FLOAT NOT NULL DEFAULT 0'],
    ['vendor', 'NVARCHAR(100)'],
    ['notes', 'NVARCHAR(500)'],
    ['attachment', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Maint_Equipment FOREIGN KEY (equipmentId) REFERENCES Equipment(id) ON DELETE CASCADE'],
  ]},
  { name: 'InventoryItem', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['name', 'NVARCHAR(150) NOT NULL'],
    ['category', 'NVARCHAR(50)'],
    ['description', 'NVARCHAR(500)'],
    ['unit', 'NVARCHAR(20)'],
    ['quantity', 'INT NOT NULL DEFAULT 0'],
    ['reorderLevel', 'INT NOT NULL DEFAULT 0'],
    ['purchasePrice', 'FLOAT'],
    ['salePrice', 'FLOAT'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Active\''],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Inventory_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'PosSale', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['saleNo', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['date', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['cashierId', 'NVARCHAR(50)'],
    ['total', 'FLOAT NOT NULL'],
    ['paymentMethod', 'NVARCHAR(20) NOT NULL'],
    ['paymentAccountId', 'NVARCHAR(50)'],
    ['voucherId', 'NVARCHAR(50)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Completed\''],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_PosSale_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_PosSale_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id)'],
  ]},
  { name: 'PosSaleLine', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['saleId', 'NVARCHAR(50) NOT NULL'],
    ['inventoryItemId', 'NVARCHAR(50) NOT NULL'],
    ['quantity', 'INT NOT NULL'],
    ['unitPrice', 'FLOAT NOT NULL'],
    ['amount', 'FLOAT NOT NULL'],
    ['CONSTRAINT FK_PosLine_Sale FOREIGN KEY (saleId) REFERENCES PosSales(id) ON DELETE CASCADE'],
    ['CONSTRAINT FK_PosLine_Item FOREIGN KEY (inventoryItemId) REFERENCES InventoryItems(id)'],
  ]},
  { name: 'Staff', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['employeeId', 'NVARCHAR(20) NOT NULL UNIQUE'],
    ['firstName', 'NVARCHAR(100) NOT NULL'],
    ['lastName', 'NVARCHAR(100)'],
    ['fatherGuardian', 'NVARCHAR(100)'],
    ['cnic', 'NVARCHAR(30)'],
    ['photo', 'NVARCHAR(500)'],
    ['address', 'NVARCHAR(500)'],
    ['emergencyContact', 'NVARCHAR(100)'],
    ['emergencyContactNo', 'NVARCHAR(30)'],
    ['phone', 'NVARCHAR(30)'],
    ['whatsapp', 'NVARCHAR(30)'],
    ['telephone', 'NVARCHAR(30)'],
    ['fax', 'NVARCHAR(30)'],
    ['email', 'NVARCHAR(150)'],
    ['joiningDate', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['department', 'NVARCHAR(50)'],
    ['designation', 'NVARCHAR(50)'],
    ['isTrainer', 'BIT NOT NULL DEFAULT 0'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['shiftId', 'NVARCHAR(50)'],
    ['basicSalary', 'FLOAT NOT NULL DEFAULT 0'],
    ['fuelAllowance', 'FLOAT NOT NULL DEFAULT 0'],
    ['rentAllowance', 'FLOAT NOT NULL DEFAULT 0'],
    ['houseAllowance', 'FLOAT NOT NULL DEFAULT 0'],
    ['otherAllowance', 'FLOAT NOT NULL DEFAULT 0'],
    ['sessi', 'FLOAT NOT NULL DEFAULT 0'],
    ['eobi', 'FLOAT NOT NULL DEFAULT 0'],
    ['fbrTaxNumber', 'NVARCHAR(50)'],
    ['overtimeAllowed', 'BIT NOT NULL DEFAULT 0'],
    ['overtimeRate', 'FLOAT NOT NULL DEFAULT 0'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['isDeleted', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Staff_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_Staff_Shift FOREIGN KEY (shiftId) REFERENCES Shifts(id)'],
  ]},
  { name: 'Shift', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(50) NOT NULL'],
    ['timeIn', 'NVARCHAR(10) NOT NULL'],
    ['timeOut', 'NVARCHAR(10) NOT NULL'],
    ['workingDays', 'NVARCHAR(100) NOT NULL'],
    ['branchId', 'NVARCHAR(50)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Shift_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'CalendarDay', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['date', 'DATETIME2 NOT NULL UNIQUE'],
    ['branchId', 'NVARCHAR(50)'],
    ['dayType', 'NVARCHAR(30) NOT NULL'],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Calendar_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
  ]},
  { name: 'Leave', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['staffId', 'NVARCHAR(50) NOT NULL'],
    ['leaveType', 'NVARCHAR(30) NOT NULL'],
    ['fromDate', 'DATETIME2 NOT NULL'],
    ['toDate', 'DATETIME2 NOT NULL'],
    ['days', 'INT NOT NULL'],
    ['reason', 'NVARCHAR(500)'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Pending\''],
    ['approvedBy', 'NVARCHAR(50)'],
    ['approvedAt', 'DATETIME2'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Leave_Staff FOREIGN KEY (staffId) REFERENCES Staff(id) ON DELETE CASCADE'],
  ]},
  { name: 'Overtime', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['staffId', 'NVARCHAR(50) NOT NULL'],
    ['date', 'DATETIME2 NOT NULL'],
    ['hours', 'FLOAT NOT NULL'],
    ['rate', 'FLOAT NOT NULL'],
    ['amount', 'FLOAT NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Pending\''],
    ['approvedBy', 'NVARCHAR(50)'],
    ['approvedAt', 'DATETIME2'],
    ['notes', 'NVARCHAR(500)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Overtime_Staff FOREIGN KEY (staffId) REFERENCES Staff(id) ON DELETE CASCADE'],
  ]},
  { name: 'Payroll', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['payrollNo', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['staffId', 'NVARCHAR(50) NOT NULL'],
    ['branchId', 'NVARCHAR(50) NOT NULL'],
    ['month', 'INT NOT NULL'],
    ['year', 'INT NOT NULL'],
    ['basicSalary', 'FLOAT NOT NULL'],
    ['totalAllowances', 'FLOAT NOT NULL'],
    ['overtimeAmount', 'FLOAT NOT NULL'],
    ['totalEarnings', 'FLOAT NOT NULL'],
    ['totalDeductions', 'FLOAT NOT NULL'],
    ['netPay', 'FLOAT NOT NULL'],
    ['status', 'NVARCHAR(20) NOT NULL DEFAULT \'Draft\''],
    ['voucherId', 'NVARCHAR(50)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT FK_Payroll_Staff FOREIGN KEY (staffId) REFERENCES Staff(id)'],
    ['CONSTRAINT FK_Payroll_Branch FOREIGN KEY (branchId) REFERENCES Branches(id)'],
    ['CONSTRAINT FK_Payroll_Voucher FOREIGN KEY (voucherId) REFERENCES Vouchers(id)'],
    ['CONSTRAINT UQ_Payroll_StaffMonthYear UNIQUE (staffId, month, year)'],
  ]},
  { name: 'LeaveType', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['allowedDays', 'INT NOT NULL'],
    ['isPaid', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'Allowance', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['name', 'NVARCHAR(50) NOT NULL UNIQUE'],
    ['description', 'NVARCHAR(500)'],
    ['isStatutory', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
  ]},
  { name: 'MasterFile', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['masterType', 'NVARCHAR(50) NOT NULL'],
    ['code', 'NVARCHAR(20) NOT NULL'],
    ['name', 'NVARCHAR(100) NOT NULL'],
    ['description', 'NVARCHAR(500)'],
    ['isActive', 'BIT NOT NULL DEFAULT 1'],
    ['extra', 'NVARCHAR(MAX)'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT UQ_MasterFile_TypeCode UNIQUE (masterType, code)'],
    ['CONSTRAINT UQ_MasterFile_TypeName UNIQUE (masterType, name)'],
  ]},
  { name: 'UserReportFormat', cols: [
    ['id', 'NVARCHAR(50) PRIMARY KEY'],
    ['userId', 'NVARCHAR(50) NOT NULL'],
    ['reportKey', 'NVARCHAR(50) NOT NULL'],
    ['name', 'NVARCHAR(100) NOT NULL'],
    ['columns', 'NVARCHAR(MAX)'],
    ['isDefault', 'BIT NOT NULL DEFAULT 0'],
    ['createdAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['updatedAt', 'DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()'],
    ['CONSTRAINT UQ_UserReportFormat UNIQUE (userId, reportKey, name)'],
  ]},
]

// Prisma's default table name is the model name (singular). For SQL Server, we'll
// use the same naming so the queries in the API can be adjusted via Prisma's
// SQL Server connector. But the CREATE TABLE statements below use the model
// names as-is to match what the Prisma Client expects.
async function main() {
  const out: string[] = []
  out.push('-- ============================================================================')
  out.push('-- Contoura Gym Management System — SQL Server schema + seed script')
  out.push('-- Compatible with: SQL Server 2019+ (also works on SQL Server Express)')
  out.push('-- Generated: ' + new Date().toISOString())
  out.push('--')
  out.push('-- How to use:')
  out.push('--   1. Open SQL Server Management Studio (SSMS)')
  out.push('--   2. Connect to your SQL Server instance')
  out.push('--   3. Right-click Databases → New Database → name it "GymDB"')
  out.push('--   4. Open a New Query window, paste this entire script, and Execute (F5)')
  out.push('--   5. Update the app\'s DATABASE_URL to point to SQL Server and run `prisma db push`')
  out.push('-- ============================================================================')
  out.push('')
  out.push('USE [GymDB];')
  out.push('GO')
  out.push('')
  out.push('SET NOCOUNT ON;')
  out.push('')

  for (const t of tables) {
    out.push('-- -----------------------------------------------------------')
    out.push(`-- Table: ${t.name}`)
    out.push('-- -----------------------------------------------------------')
    out.push(`IF OBJECT_ID(N'${t.name}', N'U') IS NOT NULL DROP TABLE [${t.name}];`)
    out.push(`CREATE TABLE [${t.name}] (`)
    const normalCols = t.cols.filter(c => !c[0].startsWith('CONSTRAINT'))
    const constraints = t.cols.filter(c => c[0].startsWith('CONSTRAINT'))
    const allLines = [...normalCols.map(c => `    [${c[0]}] ${c[1]}`), ...constraints.map(c => `    ${c[1]}`)]
    out.push(allLines.join(',\n'))
    out.push(');')
    out.push('')
  }

  out.push('GO')
  out.push('')
  out.push('-- ============================================================================')
  out.push('-- Seed Data')
  out.push('-- ============================================================================')
  out.push('')

  // For each table, dump rows. We use the Prisma Client to read.
  // Note: we skip Session/AuditLog/CalendarDay (transient/empty)
  const tablesToSeed = ['Company', 'Branch', 'Role', 'Permission', 'RolePermission', 'User', 'Account', 'TaxHead', 'AccountMapping', 'FinancialYear', 'AccountingPeriod', 'MembershipPlan', 'Shift', 'LeaveType', 'Allowance', 'Staff', 'MasterFile']

  for (const modelName of tablesToSeed) {
    const rows = await (db as any)[modelName.charAt(0).toLowerCase() + modelName.slice(1)].findMany()
    if (rows.length === 0) continue
    out.push(`-- ${modelName} (${rows.length} rows)`)
    for (const row of rows) {
      const cols = Object.keys(row)
      const vals = cols.map(c => {
        const v = row[c]
        if (v === null || v === undefined) return 'NULL'
        if (typeof v === 'number') return String(v)
        if (typeof v === 'boolean') return v ? '1' : '0'
        if (v instanceof Date) return `'${v.toISOString()}'`
        return `'${String(v).replace(/'/g, "''")}'`
      })
      out.push(`INSERT INTO [${modelName}] (${cols.map(c => `[${c}]`).join(', ')}) VALUES (${vals.join(', ')});`)
    }
    out.push('')
  }

  out.push('GO')
  out.push('')
  out.push('-- ============================================================================')
  out.push('-- Done. The database is ready.')
  out.push('-- Login: admin / admin123')
  out.push('-- ============================================================================')

  writeFileSync('database_sqlserver.sql', out.join('\n'))
  console.log(`SQL Server script written to database_sqlserver.sql (${out.length} lines)`)
}

main().then(() => db.$disconnect()).catch(e => { console.error(e); process.exit(1) })
