/**
 * Joi schemas for the Finance module.
 * Structural validation lives here; accounting rules (balance, account
 * status, periods, tags, date immutability) are enforced by the posting
 * engine SPs — the backend never trusts frontend validation.
 */
const Joi = require('joi');

const ACCOUNT_TYPES = ['Asset', 'Liability', 'Capital', 'Revenue', 'Expense'];
const FINANCE_TAGS = ['Customer', 'Vendor', 'Bank', 'Cash', 'Employee', 'Tax'];
const TAX_TYPES = ['Withholding', 'SalesTax', 'Other'];

const accountProfileFields = {
  Description: Joi.string().max(500).allow('', null).optional(),
  ReferenceNo: Joi.string().max(50).allow('', null).optional(),
  Address: Joi.string().max(500).allow('', null).optional(),
  Phone: Joi.string().max(30).allow('', null).optional(),
  Whatsapp: Joi.string().max(30).allow('', null).optional(),
  Telephone: Joi.string().max(30).allow('', null).optional(),
  Fax: Joi.string().max(30).allow('', null).optional(),
  Email: Joi.string().max(150).allow('', null).optional(),
  Cnic: Joi.string().max(20).allow('', null).optional(),
  Ntn: Joi.string().max(20).allow('', null).optional(),
  Strn: Joi.string().max(20).allow('', null).optional(),
  BankName: Joi.string().max(150).allow('', null).optional(),
  BankAccountTitle: Joi.string().max(150).allow('', null).optional(),
  BankAccountNo: Joi.string().max(50).allow('', null).optional(),
  IBAN: Joi.string().max(50).allow('', null).optional(),
  BankBranch: Joi.string().max(150).allow('', null).optional(),
};

const accountCreateSchema = Joi.object({
  Title: Joi.string().trim().max(150).required(),
  // codes are generated by the backend from the parent — never supplied by users
  ParentAccountID: Joi.number().integer().positive().required()
    .messages({ 'any.required': 'Select a parent account — the code is generated from it.' }),
  IsControl: Joi.boolean().default(false),
  KnockOff: Joi.boolean().default(false),
  BookType: Joi.string().valid('Cash Book', 'Bank Book').allow(null, '').optional(),
  BranchID: Joi.number().integer().positive().allow(null).optional(),
  IsActive: Joi.boolean().default(true),
  ...accountProfileFields,
  Tags: Joi.array().items(Joi.string().trim().max(30)).max(10).allow(null).optional(),
});

const accountUpdateSchema = Joi.object({
  Title: Joi.string().trim().max(150).required(),
  KnockOff: Joi.boolean().allow(null).optional(),
  BookType: Joi.string().valid('Cash Book', 'Bank Book').allow(null, '').optional(),
  BranchID: Joi.number().integer().positive().allow(null).optional(),
  IsActive: Joi.boolean().allow(null).optional(),
  ...accountProfileFields,
  Tags: Joi.array().items(Joi.string().trim().max(30)).max(10).allow(null).optional(),
});

const accountStatusSchema = Joi.object({
  IsActive: Joi.boolean().required(),
});

const coaStructureSchema = Joi.object({
  Levels: Joi.array().items(Joi.number().integer().min(1).max(12)).min(1).max(7).required()
    .custom((value, helpers) => {
      const total = value.reduce((s, d) => s + d, 0);
      if (total > 12) return helpers.error('any.invalid');
      return value;
    }, 'total digits rule')
    .message({ 'any.invalid': 'COA structure cannot exceed 12 total digits.' }),
});

const yearCreateSchema = Joi.object({
  Name: Joi.string().trim().max(50).required(),
  StartDate: Joi.date().required(),
  EndDate: Joi.date().required(),
});

const yearStatusSchema = Joi.object({
  Status: Joi.string().valid('Open', 'Locked').required(),
});

const yearCloseSchema = Joi.object({
  RetainedEarningsAccountID: Joi.number().integer().positive().allow(null).optional(),
});

const periodStatusSchema = Joi.object({
  Status: Joi.string().valid('Open', 'Closed', 'Locked').required(),
});

const voucherTypeUpdateSchema = Joi.object({
  Title: Joi.string().trim().max(100).allow('', null).optional(),
  Prefix: Joi.string().trim().max(10).allow('', null).optional(),
  IsActive: Joi.boolean().allow(null).optional(),
});

const mappingSchema = Joi.object({
  MappingType: Joi.string().valid('PaymentMethod', 'Payroll',
    'MembershipRevenue', 'DefaultCash', 'DefaultBank', 'BankAccount', 'CashAccount').required(),
  SourceKey: Joi.string().trim().max(50).allow('', null).optional(),
  AccountID: Joi.number().integer().positive().required(),
});

const formatSaveSchema = Joi.object({
  FormatID: Joi.number().integer().positive().allow(null).optional(),
  ReportKey: Joi.string().trim().max(50).required(),
  FormatName: Joi.string().trim().max(100).required(),
  Columns: Joi.array().items(Joi.object({
    key: Joi.string().max(60).required(),
    label: Joi.string().max(100).allow('', null).optional(),
    visible: Joi.boolean().default(true),
    order: Joi.number().integer().min(0).default(0),
  })).min(1).required(),
  IsDefault: Joi.boolean().default(false),
});

const reconCreateSchema = Joi.object({
  AccountID: Joi.number().integer().positive().required(),
  StatementDate: Joi.date().required(),
  StatementOpeningBalance: Joi.number().precision(2).default(0),
  StatementClosingBalance: Joi.number().precision(2).default(0),
  BranchID: Joi.number().integer().positive().allow(null).optional(),
  Notes: Joi.string().max(500).allow('', null).optional(),
});

const reconLineSchema = Joi.object({
  IsReconciled: Joi.boolean().required(),
});

const defaultsSchema = Joi.object({
  Key: Joi.string().valid('FinanceCompany', 'FinanceAccounting', 'FinanceVoucherNumbering', 'FinanceReports').required(),
  Value: Joi.object().required(),
});

/* ================================================================== */
/* VOUCHER DOCUMENTS                                                  */
/* CASH / BANK: header money account + Amount-only lines — the        */
/* engine derives Debit/Credit from the direction.                    */
/* JOURNAL / OTB: explicit Debit / Credit lines; must balance.        */
/* ================================================================== */

const simpleLineSchema = Joi.object({
  AccountID: Joi.number().integer().positive().required(),
  Description: Joi.string().max(500).allow('', null).optional(),
  Amount: Joi.number().precision(2).greater(0).required()
    .messages({ 'number.greater': 'Every line amount must be greater than zero.' }),
  TaxHeadID: Joi.number().integer().positive().allow(null).optional(),
  TaxAccountID: Joi.number().integer().positive().allow(null).optional(),
  TaxPercent: Joi.number().precision(4).min(0).max(100).allow(null).optional(),
  TaxAmount: Joi.number().precision(2).min(0).allow(null).optional(),
  ChequeNo: Joi.string().max(50).allow('', null).optional(),
  ChequeStatus: Joi.string().valid('Hold', 'Pending', 'Cleared', 'Bounced', 'Cancelled').allow(null, '').optional(),
  ChequeTitle: Joi.string().max(150).allow('', null).optional(),
  ReferenceNo: Joi.string().max(50).allow('', null).optional(),
  KnockOff: Joi.boolean().default(false),
  BillRef: Joi.string().max(50).allow('', null).optional(),
  BillDate: Joi.date().allow(null).optional(),
  DueDate: Joi.date().allow(null).optional(),
  PartyMemberID: Joi.number().integer().positive().allow(null).optional(),
  PartySupplierID: Joi.number().integer().positive().allow(null).optional(),
  PartyStaffID: Joi.number().integer().positive().allow(null).optional(),
}).custom((value, helpers) => {
  // a user must not inject ledger sides through a simple voucher
  if (value.Debit !== undefined || value.Credit !== undefined) return helpers.error('any.invalid');
  // tax rule: percent/amount present => TaxAccountID mandatory (Rule: Part 8)
  const pct = Number(value.TaxPercent || 0);
  const amt = Number(value.TaxAmount || 0);
  if ((pct > 0 || amt > 0) && !value.TaxAccountID) return helpers.error('any.invalid');
  return value;
}, 'simple line rule').message({
  'any.invalid': 'Debit/Credit are automatic for Cash and Bank vouchers — send Amount only. Tax Account is mandatory when tax percentage or tax amount is used.',
});

const balancedLineSchema = Joi.object({
  AccountID: Joi.number().integer().positive().required(),
  Description: Joi.string().max(500).allow('', null).optional(),
  Debit: Joi.number().precision(2).min(0).default(0),
  Credit: Joi.number().precision(2).min(0).default(0),
}).custom((value, helpers) => {
  const d = value.Debit || 0;
  const c = value.Credit || 0;
  if (d > 0 && c > 0) return helpers.error('any.invalid');
  if (d === 0 && c === 0) return helpers.error('any.invalid');
  return value;
}, 'balanced line rule').message({
  'any.invalid': 'Each line must have exactly one of Debit or Credit, greater than zero.',
});

const documentSchema = Joi.object({
  Family: Joi.string().valid('CASH', 'BANK', 'JOURNAL', 'OTB').required(),
  Status: Joi.string().valid('Posted', 'Draft', 'Hold').default('Posted'),
  Direction: Joi.string().valid('Receipt', 'Payment')
    .when('Family', { is: 'CASH', then: Joi.required() })
    .when('Family', { is: 'BANK', then: Joi.required() })
    .when('Family', { is: 'JOURNAL', then: Joi.valid(null) })
    .when('Family', { is: 'OTB', then: Joi.valid(null) }),
  MoneyAccountID: Joi.number().integer().positive()
    .when('Family', { is: 'CASH', then: Joi.required() })
    .when('Family', { is: 'BANK', then: Joi.required() })
    .when('Family', { is: 'JOURNAL', then: Joi.valid(null) })
    .when('Family', { is: 'OTB', then: Joi.valid(null) }),
  VoucherDate: Joi.date().required(),
  BranchID: Joi.number().integer().positive().allow(null).optional(),
  Narrative: Joi.string().max(200).allow('', null).optional()
    .messages({ 'string.max': 'Voucher description cannot exceed 200 characters.' }),
  Lines: Joi.array()
    .when('Family', {
      is: 'CASH', then: Joi.array().items(simpleLineSchema).min(1).required(),
    })
    .when('Family', {
      is: 'BANK', then: Joi.array().items(simpleLineSchema).min(1).required(),
    })
    .when('Family', {
      is: 'JOURNAL', then: Joi.array().items(balancedLineSchema).min(2).required(),
    })
    .when('Family', {
      is: 'OTB', then: Joi.array().items(balancedLineSchema).min(2).required(),
    }),
}).messages({
  'array.min': 'Add at least one detail line (a journal / opening voucher needs at least two).',
});

const taxHeadCreateSchema = Joi.object({
  Code: Joi.string().trim().max(20).required(),
  Name: Joi.string().trim().max(150).required(),
  Description: Joi.string().max(500).allow('', null).optional(),
  RatePercent: Joi.number().precision(4).min(0).max(100).allow(null).optional(),
  TaxType: Joi.string().valid(...TAX_TYPES).allow(null, '').optional(),
});

const taxHeadUpdateSchema = Joi.object({
  Name: Joi.string().trim().max(150).required(),
  Description: Joi.string().max(500).allow('', null).optional(),
  RatePercent: Joi.number().precision(4).min(0).max(100).allow(null).optional(),
  TaxType: Joi.string().valid(...TAX_TYPES).allow(null, '').optional(),
});

module.exports = {
  ACCOUNT_TYPES,
  FINANCE_TAGS,
  TAX_TYPES,
  documentSchema,
  taxHeadCreateSchema,
  taxHeadUpdateSchema,
  accountCreateSchema,
  accountUpdateSchema,
  accountStatusSchema,
  coaStructureSchema,
  yearCreateSchema,
  yearStatusSchema,
  yearCloseSchema,
  periodStatusSchema,
  voucherTypeUpdateSchema,
  mappingSchema,
  formatSaveSchema,
  reconCreateSchema,
  reconLineSchema,
  defaultsSchema,
};
